// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNnOoGUFWBDD7Fn6RAHiRDNBqHa4nP-Y',
    appId: '1:250441676567:web:c4e16499eda29fe97ea952',
    messagingSenderId: '250441676567',
    projectId: 'kit305-7baa4',
    authDomain: 'kit305-7baa4.firebaseapp.com',
    storageBucket: 'kit305-7baa4.appspot.com',
    measurementId: 'G-LYZHYFSPFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4b6JEsRuZqwU9TT7XC8M16gCxLOQunw',
    appId: '1:250441676567:android:8b915bb1992f92a37ea952',
    messagingSenderId: '250441676567',
    projectId: 'kit305-7baa4',
    storageBucket: 'kit305-7baa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmm_rWXb7DHva3LOcZTost6T7LHUCYtv0',
    appId: '1:250441676567:ios:a8271ec776316b417ea952',
    messagingSenderId: '250441676567',
    projectId: 'kit305-7baa4',
    storageBucket: 'kit305-7baa4.appspot.com',
    iosClientId: '250441676567-8v1tptdul9e9hnmleff6c8tcbvt6qduf.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmm_rWXb7DHva3LOcZTost6T7LHUCYtv0',
    appId: '1:250441676567:ios:20aaea93b7b5fe4c7ea952',
    messagingSenderId: '250441676567',
    projectId: 'kit305-7baa4',
    storageBucket: 'kit305-7baa4.appspot.com',
    iosClientId: '250441676567-iluq2usjq7n7utq25e10t5snl16fu9r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyApp.RunnerTests',
  );
}
